apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
  namespace: default
spec:
  oidc:
    authEndpoint: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth
    clientID: nginx-plus
    clientSecret: oidc-secret
    jwksURI: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/certs
    scope: openid+profile+email
    tokenEndpoint: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/token
